# Header
menu:
  Home: /
  Archives: /archives
  About: /about

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
# sidebar: none
# widgets:
# - recent_posts
# - category
# - tagcloud

# copyright: |-
#   <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-nd/4.0/88x31.png" /></a></br>
#   All website licensed under <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a></br>

# toc open 
toc:
  enable: true
  default: false

# Widget behavior
archive_type: 'monthly'
show_count: false
recent_posts_limits: 5


# favicon: /favicon.ico
# rss: /atom.xml

# valine comment system. https://valine.js.org
valine:
  enable: false # if you want use valine,please set this value is true
  appId:  # leancloud application app id
  appKey:  # leancloud application app key
  notify: false # valine mail notify (true/false) https://github.com/xCss/Valine/wiki
  verify: false # valine verify code (true/false)
  pageSize: 10 # comment list page size
  avatar: mm # gravatar style https://valine.js.org/#/avatar
  lang: zh-cn # i18n: zh-cn/en
  placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )
  guest_info: nick,mail,link #valine comment header info

math:
  enable: true
  engine: katex